### ISSUE TITLE
Unable to Activate Neon

### ISSUE THREAD

**Issue by dodango** [OGFaisalN/Synthwave-2077#1]
Command for enabling and disabling Neon does not exist.

**Comment by faisalnjs** [comment]
Thank you for letting me know about this issue. The built in neon effects may not render on some older VSCode versions.

- I have added instructions on how to enable neon with the theme, check the updated [`README.md`](https://github.com/faisalnjs/Synthwave-2077/blob/main/README.md). Be sure to follow the requirements stated in the README.
- The [`synthwave.css`](https://github.com/faisalnjs/Synthwave-2077/blob/main/synthwave.css) file has been added to the repository, you can use that along with the [_Custom CSS and JS Loader_](https://github.com/be5invis/vscode-custom-css) VSCode extension to render the neon effect.

Follow up on this thread if you experience any issues activating the neon effect. Thank you.
